[memory.flash]
size = "1M"
origin = 0x08000000

[memory.ram]
size = "256K"
origin = 0x20000000

[heap]
size = "128K"
pools = [
    { block = "4", capacity = 1511 },
    { block = "36", capacity = 415 },
    { block = "216", capacity = 96 },
    { block = "644", capacity = 39 },
    { block = "1412", capacity = 17 },
    { block = "2600", capacity = 8 },
    { block = "4292", capacity = 3 },
    { block = "6556", capacity = 1 },
]

[probe]
gdb-client-command = "gdb-multiarch"

[probe.openocd]
command = "openocd"
port = 3333
<<<<<<< HEAD
arguments = ["-f", "interface/stlink-v2-1.cfg", "-f", "target/stm32f4x.cfg"]


=======
arguments = ["-f", "interface/stlink.cfg", "-f", "target/stm32f4x.cfg"]
>>>>>>> c3d8ff8605a490a33dce93530509fba48adf955b

[log.swo]
reset-freq = 16000000
baud-rate = 115200
serial-endpoint = "/dev/ttyACM0"
