[memory.flash]
size = "1M"
origin = 0x08000000

[memory.ram]
size = "256K"
origin = 0x20000000

[heap]
size = "128K"
pools = [
    { block = "4", capacity = 1511 },
    { block = "36", capacity = 415 },
    { block = "216", capacity = 96 },
    { block = "644", capacity = 39 },
    { block = "1412", capacity = 17 },
    { block = "2600", capacity = 8 },
    { block = "4292", capacity = 3 },
    { block = "6556", capacity = 1 },
]

[probe]
gdb-client-command = "gdb-multiarch"

[probe.bmp]
device = "stm32f412"
gdb-endpoint = "/dev/ttyACM1"

[log.swo]
reset-freq = 16000000
baud-rate = 115200
serial-endpoint = "/dev/ttyACM1"
